# Generated by Django 5.2.10 on 2026-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkfit', '0007_alter_reminder_remind_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
